#!/usr/bin/env python3
"""
QDUC Web Application Backend
Handles parameter input and executes nuclear reaction calculations
"""

from flask import Flask, render_template, request, jsonify
import subprocess
import os
import shutil

app = Flask(__name__)

# Configuration
QDUC_DIR = os.path.dirname(os.path.abspath(__file__))
INPUTS_DIR = os.path.join(QDUC_DIR, 'Inputs')
OUTPUTS_DIR = os.path.join(QDUC_DIR, 'Outputs')

@app.route('/')
def index():
    """Serve the main HTML page"""
    return open('qduc_app.html').read()

@app.route('/run-calculation', methods=['POST'])
def run_calculation():
    """
    Handle calculation request from the web form
    Generates modified run_all.sh and executes it
    """
    try:
        data = request.json
        
        # Extract parameters
        reaction_name = data['reactionName']
        beam_energy = data['beamEnergy']
        target_a = data['targetA']
        target_z = data['targetZ']
        orbital = data['orbital']
        nodes = data['nodes']
        q_value = data['qValue']
        target_spin = data['targetSpin']
        final_spin = data['finalSpin']
        
        # Parse orbital
        l, j = orbital.split(',')
        
        # Generate the modified run_all.sh script
        script_content = generate_run_script(
            reaction_name, beam_energy, target_a, target_z,
            l, j, nodes, q_value, target_spin, final_spin
        )
        
        # Write the script
        script_path = os.path.join(QDUC_DIR, 'run_calculation_temp.sh')
        with open(script_path, 'w') as f:
            f.write(script_content)
        
        # Make it executable
        os.chmod(script_path, 0o755)
        
        # Clean old outputs
        if os.path.exists(INPUTS_DIR):
            shutil.rmtree(INPUTS_DIR)
        if os.path.exists(OUTPUTS_DIR):
            shutil.rmtree(OUTPUTS_DIR)
        os.makedirs(INPUTS_DIR, exist_ok=True)
        os.makedirs(OUTPUTS_DIR, exist_ok=True)
        
        # Execute the calculation in the background
        process = subprocess.Popen(
            ['bash', script_path],
            cwd=QDUC_DIR,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        
        return jsonify({
            'success': True,
            'message': f'Calculation started! Running 416 iterations for {reaction_name}. Check terminal for progress.',
            'pid': process.pid
        })
        
    except Exception as e:
        return jsonify({
            'success': False,
            'message': str(e)
        }), 500

def generate_run_script(name, energy, a, z, l, j, nodes, q, target_spin, final_spin):
    """Generate the bash script with user parameters"""
    
    script = f'''#!/bin/bash

# Auto-generated QDUC calculation script
# Reaction: {name}
# Generated by QDUC Web App

# First set of input lines
fixed_lines1=(
  "2"
  "0"
  "0"
  "{energy}"
  "{a} {z}"
  "1"
  "1"
  "0 0 0"
  "{l} {j}"
  "{nodes}"
  "2"
  "{q}"
  "1"
  "{target_spin}"
  "1"
  "6"
  "4"
  "1"
  "{final_spin}"
  "1"
  "7"
)

# Second set of input lines (optical model parameters)
fixed_lines2=(
  "5"
  "1"
  "3"
  "1"
  "2"
  "1.25 0.65"
  "6"
  "0"
  "1.1"
  "0.65"
)

# Loop from 1 to 416
inputs_dir="Inputs"
outputs_dir="Outputs"
mkdir -p "$inputs_dir"
mkdir -p "$outputs_dir"

echo "Starting calculation for {name}..."
echo "Target: A={a}, Z={z}"
echo "Beam energy: {energy} MeV"
echo "Orbital: l={l}, j={j}"
echo "Q-value: {q} MeV"
echo ""

for i in $(seq 1 416); do

  filename="$inputs_dir/input.$i"

  # Create the input file
  rm -f input.front
  {{

    # Info lines
    echo "{name}$i"
    echo "Running with KDUQ parameter set $i"

    # Print first set of fixed lines
    for line in "${{fixed_lines1[@]}}"; do
      echo "$line"
    done

    # Add the KDUQ parameter set number
    echo "$i"
    echo "5"
    echo "$i"

    # Print second set of fixed lines
    for line in "${{fixed_lines2[@]}}"; do
      echo "$line"
    done

  }} > $filename

  # Run FRONT_KDUQ
  ./FRONT_KDUQ < $filename > /dev/null 2>&1

  # Setup TWOFNR input
  tranfile="tran.{name}$i"
  twofnr_input="twofnr.input"
  echo $tranfile > $twofnr_input

  # Run TWOFNR
  ./TWOFNR < $twofnr_input > /dev/null 2>&1

  # Move outputs
  mv *.{name}* $outputs_dir/ 2>/dev/null

  # Progress indicator
  if [ $((i % 50)) -eq 0 ]; then
    echo "Progress: $i/416 iterations complete"
  fi

done

echo ""
echo "✓ All 416 iterations complete!"
echo "✓ Outputs saved to: $outputs_dir/"
echo ""
echo "Next steps:"
echo "  1. Run analysis: python3.11 mean1.py"
echo "  2. Generate plot: python3.11 plot_results.py"
'''
    
    return script

if __name__ == '__main__':
    print("="*60)
    print("QDUC Web Application Server")
    print("="*60)
    print(f"Working directory: {QDUC_DIR}")
    print(f"Open your browser to: http://localhost:8000")
    print("="*60)
    print()
    
    app.run(debug=True, host='0.0.0.0', port=8000)
