#!/bin/bash

# Auto-generated QDUC calculation script
# Reaction: 36S_dp
# Generated by QDUC Web App

# First set of input lines
fixed_lines1=(
  "2"
  "0"
  "0"
  "8.0"
  "36 16"
  "1"
  "1"
  "0 0 0"
  "3 3.5"
  "0"
  "2"
  "4.0"
  "1"
  "0"
  "1"
  "6"
  "4"
  "1"
  "3.5"
  "1"
  "7"
)

# Second set of input lines (optical model parameters)
fixed_lines2=(
  "5"
  "1"
  "3"
  "1"
  "2"
  "1.25 0.65"
  "6"
  "0"
  "1.1"
  "0.65"
)

# Loop from 1 to 416
inputs_dir="Inputs"
outputs_dir="Outputs"
mkdir -p "$inputs_dir"
mkdir -p "$outputs_dir"

echo "Starting calculation for 36S_dp..."
echo "Target: A=36, Z=16"
echo "Beam energy: 8.0 MeV"
echo "Orbital: l=3, j=3.5"
echo "Q-value: 4.0 MeV"
echo ""

for i in $(seq 1 416); do

  filename="$inputs_dir/input.$i"

  # Create the input file
  rm -f input.front
  {

    # Info lines
    echo "36S_dp$i"
    echo "Running with KDUQ parameter set $i"

    # Print first set of fixed lines
    for line in "${fixed_lines1[@]}"; do
      echo "$line"
    done

    # Add the KDUQ parameter set number
    echo "$i"
    echo "5"
    echo "$i"

    # Print second set of fixed lines
    for line in "${fixed_lines2[@]}"; do
      echo "$line"
    done

  } > $filename

  # Run FRONT_KDUQ
  ./FRONT_KDUQ < $filename > /dev/null 2>&1

  # Setup TWOFNR input
  tranfile="tran.36S_dp$i"
  twofnr_input="twofnr.input"
  echo $tranfile > $twofnr_input

  # Run TWOFNR
  ./TWOFNR < $twofnr_input > /dev/null 2>&1

  # Move outputs
  mv *.36S_dp* $outputs_dir/ 2>/dev/null

  # Progress indicator
  if [ $((i % 50)) -eq 0 ]; then
    echo "Progress: $i/416 iterations complete"
  fi

done

echo ""
echo "✓ All 416 iterations complete!"
echo "✓ Outputs saved to: $outputs_dir/"
echo ""
echo "Next steps:"
echo "  1. Run analysis: python3.11 mean1.py"
echo "  2. Generate plot: python3.11 plot_results.py"
