
ALL: num_to_letter convert_to_xmgrace 


num_to_letter: num_to_letter.o
	g++  num_to_letter.o -o num_to_letter

num_to_letter.o: num_to_letter.cpp
	g++  -c num_to_letter.cpp  


convert_to_xmgrace: convert_to_xmgrace.o
	g++  convert_to_xmgrace.o -o convert_to_xmgrace

convert_to_xmgrace.o: convert_to_xmgrace.cpp
	g++  -c convert_to_xmgrace.cpp  
	